"""NLU Engine — LLM-first tool selection for Telegram messages.

Replaces the old IntentClassifier (domain/metric menu picker) and
EntityResolver (keyword extraction) with a single LLM call that:
- Understands the user's intent in context
- Extracts entities from raw text (no pre-processing needed)
- Selects the appropriate tool and its parameters
- Returns confidence and clarification needs

The LLM receives tool descriptions generated by ToolRegistry so new
tools are automatically discoverable without code changes.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from typing import Any

from backend.app.application.telegram.llm import LLMProvider
from backend.app.application.telegram.tool_registry import build_tools_prompt

logger = logging.getLogger(__name__)


@dataclass
class NLUResult:
    """Output of the NLU engine — a tool invocation decision."""
    tool: str
    params: dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    needs_clarification: bool = False
    clarification_question: str = ""


NLU_SYSTEM_PROMPT = """Eres el motor NLU de un sistema de turnos médicos militares (hospital militar).
Tu trabajo es entender qué quiere el usuario y decidir qué herramienta usar.

{tools_section}

CONTEXTO DE CONVERSACIÓN:
{conversation_context}

Responde ÚNICAMENTE con este JSON:
{{"tool": "<nombre>", "params": {{...}}, "confidence": 0.95, "needs_clarification": false, "clarification_question": ""}}

REGLAS:
- tool: elige de la lista de arriba. Usa SIEMPRE un nombre exacto.
- params: parámetros que necesita la herramienta. Extrae del texto del usuario.
  * sexo: usa "F" para femenino/mujer/doctora, "M" para masculino/hombre/doctor.
  * fechas: convierte a YYYY-MM-DD. "primer lunes de junio 2026" → calcula la fecha real (2026-06-01).
  * "este mes" → mes y año actual. "el mes pasado" → mes anterior.
  * Nombres de doctores: extrae apellidos o nombres como aparecen.
  * Nombres de departamentos/áreas: usa el nombre exacto.
- confidence: 0.0-1.0 según qué tan seguro estás.
- needs_clarification: true si la pregunta es ambigua y necesitas preguntar algo.
- clarification_question: solo si needs_clarification=true, pregunta corta al usuario.

IMPORTANTE:
- Si es un saludo ("hola", "buenos días") → tool="reply", params={{"response_type":"greeting"}}.
- Si es "gracias" o despedida → tool="reply", params={{"response_type":"farewell"}}.
- Si pregunta "qué puedes hacer" o "ayuda" → tool="reply", params={{"response_type":"help"}}.
- Preguntas de conteo ("cuántos", "cuántas") → usa count_doctors o doctors_by_sex/rank/department.
- Preguntas de listado ("muéstrame", "dame lista", "quiénes") → usa list_doctors.
- Preguntas sobre guardias/asignaciones → usa calendar_assignments o calendar_assigned_count.
- Si ninguna herramienta específica sirve y es una pregunta de datos → usa sql_query.
- NUNCA inventes datos. Solo extraes parámetros del mensaje del usuario.
- Si el usuario hace follow-up ("y de ellos", "cuáles son mujeres") usa el contexto de la conversación."""


class NLUEngine:
    """LLM-first NLU: single call for intent, entities, and tool selection."""

    def __init__(self, llm: LLMProvider) -> None:
        self._llm = llm
        self._tools_prompt = build_tools_prompt()

    def classify(
        self,
        user_text: str,
        *,
        conversation_history: list[dict[str, str]] | None = None,
    ) -> NLUResult:
        """Classify user message into a tool invocation.

        Args:
            user_text: Raw user message (no pre-processing).
            conversation_history: Prior exchanges as [{"role": "...", "content": "..."}].

        Returns:
            NLUResult with tool name, params, confidence.
        """
        context = self._format_history(conversation_history)
        system_prompt = NLU_SYSTEM_PROMPT.format(
            tools_section=self._tools_prompt,
            conversation_context=context,
        )

        messages: list[dict] = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_text},
        ]

        response = self._call_llm(messages)
        return self._parse(response)

    def _format_history(self, history: list[dict[str, str]] | None) -> str:
        if not history:
            return "(primera interacción)"
        lines = []
        for msg in history[-6:]:
            role = "Usuario" if msg.get("role") == "user" else "Bot"
            content = msg.get("content", "")[:200]
            lines.append(f"{role}: {content}")
        return "\n".join(lines)

    def _call_llm(self, messages: list[dict]) -> str:
        """Call the LLM with retry on failure."""
        try:
            response = self._llm.chat_complete(messages, temperature=0.0, json_mode=True)
            return response.strip()
        except Exception:
            try:
                response = self._llm.chat_complete(messages, temperature=0.0, json_mode=False)
                return response.strip()
            except Exception:
                return ""

    def _parse(self, response: str) -> NLUResult:
        """Parse JSON response into NLUResult."""
        if not response:
            return self._fallback()

        parsed = self._extract_json(response)
        if parsed is None:
            return self._fallback()

        return NLUResult(
            tool=parsed.get("tool", "reply"),
            params=parsed.get("params", {}),
            confidence=float(parsed.get("confidence", 0.5)),
            needs_clarification=bool(parsed.get("needs_clarification", False)),
            clarification_question=str(parsed.get("clarification_question", "")),
        )

    def _extract_json(self, text: str) -> dict | None:
        """Extract JSON from text, handling markdown code blocks."""
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            match = re.search(r'\{.*\}', text, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group(0))
                except json.JSONDecodeError:
                    pass
        return None

    def _fallback(self) -> NLUResult:
        """Conservative fallback — ask for clarification."""
        return NLUResult(
            tool="reply",
            params={"response_type": "unknown"},
            confidence=0.0,
            needs_clarification=True,
            clarification_question="No entendí bien tu consulta. ¿Podrías explicarlo de otra forma?",
        )


# ---------------------------------------------------------------------------
# Legacy IntentClassifier — kept for backward compatibility with tests
# ---------------------------------------------------------------------------

@dataclass
class ClassifiedIntent:
    """Legacy structured intent (kept for test compatibility)."""
    domain: str
    action: str
    metric: str | None = None
    query_type: str | None = None
    params: dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    response_text: str | None = None
    format: str | None = None


class IntentClassifier:
    """Legacy domain/metric classifier (backward-compatible wrapper)."""

    def __init__(self, llm: LLMProvider) -> None:
        self._engine = NLUEngine(llm)

    def classify(
        self,
        user_text: str,
        *,
        entity_hints: str = "",
        resolved_entities: dict[str, Any] | None = None,
    ) -> ClassifiedIntent:
        """Classify using the new NLU engine, return legacy format."""
        result = self._engine.classify(user_text)

        # Map tool → domain/metric for backward compat
        tool_to_domain = {
            "list_doctors": "medicos", "count_doctors": "medicos",
            "doctors_by_sex": "medicos", "doctors_by_rank": "medicos",
            "doctors_by_department": "medicos", "doctor_last_service": "medicos",
            "doctor_service_load": "medicos", "unassigned_doctors": "medicos",
            "calendar_assignments": "calendario", "calendar_assigned_count": "calendario",
            "calendar_status": "calendario",
        }
        domain = tool_to_domain.get(result.tool, "general")
        action = "reply" if result.tool == "reply" else (
            "ambiguous" if result.needs_clarification else "query"
        )

        return ClassifiedIntent(
            domain=domain,
            action=action,
            metric=result.tool if result.tool not in ("reply", "sql_query") else None,
            query_type=result.tool if result.tool not in ("reply",) else None,
            params=result.params,
            confidence=result.confidence,
            response_text=result.clarification_question if result.needs_clarification else None,
        )
