"""NLU Engine — LLM-first tool selection for Telegram messages.

Replaces the old IntentClassifier (domain/metric menu picker) and
EntityResolver (keyword extraction) with a single LLM call that:
- Understands the user's intent in context
- Extracts entities from raw text (no pre-processing needed)
- Selects the appropriate tool and its parameters
- Returns confidence and clarification needs

The LLM receives tool descriptions generated by ToolRegistry so new
tools are automatically discoverable without code changes.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import date
from typing import Any

from backend.app.application.telegram.llm import LLMProvider
from backend.app.application.telegram.tool_registry import build_tools_prompt

logger = logging.getLogger(__name__)

# weekday() de datetime: 0 = lunes.
_WEEKDAYS_ES = (
    "lunes",
    "martes",
    "miércoles",
    "jueves",
    "viernes",
    "sábado",
    "domingo",
)


@dataclass
class NLUResult:
    """Output of the NLU engine — a tool invocation decision."""
    tool: str
    params: dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    needs_clarification: bool = False
    clarification_question: str = ""


NLU_SYSTEM_PROMPT = """Eres el motor NLU de un sistema de turnos médicos militares (hospital militar).
Tu trabajo es entender qué quiere el usuario y decidir qué herramienta del catálogo usar.
El catálogo es estilo servidor MCP: cada herramienta es una capacidad concreta; las
variantes de una misma consulta son parámetros de la herramienta, no herramientas nuevas.

{tools_section}

{system_context}

FECHA DE HOY: {today} ({weekday}).
Convierte las fechas relativas con esa referencia ("hoy" → {today}, "mañana" → el día
siguiente, "ayer" → el anterior). NUNCA inventes una fecha que el usuario no dio ni
que no se deduzca de hoy.

CATALOGO DE VALORES DEL SISTEMA (usa SOLO estos valores exactos para filtros):
Rangos militares (orden jerarquico): Asimilado Militar, Raso, Cabo, Sargento, Sargento mayor, Segundo Teniente, Primer Teniente, Capitan, Mayor, Teniente Coronel, Coronel
Areas de servicio: Emergencia, Pista, Disponible
Sexo (valores en BD): M (masculino/hombre), F (femenino/mujer)

CONTEXTO DE CONVERSACIÓN:
{conversation_context}

Responde ÚNICAMENTE con este JSON:
{{"tool": "<nombre>", "params": {{...}}, "confidence": 0.95, "needs_clarification": false, "clarification_question": ""}}

REGLAS:
- tool: elige UNA herramienta del catálogo de arriba. Usa SIEMPRE un nombre exacto.
- params: parámetros que necesita la herramienta. Extrae del texto del usuario.
  * sexo: usa "F" para femenino/mujer/doctora, "M" para masculino/hombre/doctor. NO uses "female"/"male".
  * rango: usa el nombre EXACTO del catalogo de rangos de arriba. NO inventes ni modifiques.
  * service_area: usa el nombre EXACTO del catalogo de areas. NO inventes.
  * departamento: extrae tal cual lo dice el usuario.
  * fechas: convierte a YYYY-MM-DD.
  * Nombres de doctores: extrae apellidos o nombres como aparecen.
- confidence: 0.0-1.0 según qué tan seguro estás.
- needs_clarification: true si la pregunta es ambigua (falta fecha, médico o área) y no puedes
  elegir con certeza. Pon una sola pregunta corta en clarification_question.
- clarification_question: solo si needs_clarification=true.

REGLAS ESTRICTAS (contrato de comportamiento):
- Elige la herramienta cuya pregunta típica coincida con lo que pide el usuario. No existe
  herramienta de SQL: las consultas se resuelven con las herramientas del catálogo.
- Si entiendes la intención pero ninguna herramienta calza → tool="reply",
  params={{"response_type":"out_of_scope"}}.
- Si NO entiendes la petición (incoherente, sin relación con el sistema) → tool="reply",
  params={{"response_type":"clarify"}}.
- Si la petición es de ESCRITURA (asignar, aprobar, generar o modificar el calendario,
  desbloquear, eliminar, crear, editar médicos o reglas) → tool="reply",
  params={{"response_type":"out_of_scope"}}: eso se hace en el panel web.
  OJO: «generar el calendario» (crear turnos) es ESCRITURA, pero «mándame el reporte/PDF»
  es LECTURA → generate_report. Enviar un documento NO es escribir en el sistema.
- Saludo → tool="reply", params={{"response_type":"greeting"}}.
- Gracias/despedida → tool="reply", params={{"response_type":"farewell"}}.
- "Qué puedes hacer"/ayuda → tool="reply", params={{"response_type":"help"}}.
- NUNCA inventes datos, médicos, fechas ni conteos: el backend devuelve los datos reales.

DESAMBIGUACIÓN DE COLISIONES CONOCIDAS:
Varias herramientas compiten por la misma frase. NO elijas por parecido general: lee el
DISCRIMINADOR de cada bloque y decide por esa palabra clave. Cuando el bloque diga
"NO USES X", esa herramienta queda descartada aunque su descripción suene parecida.

1) FECHA vs CARACTERÍSTICAS vs HISTORIAL
   Tools: calendar_assignments / list_doctors / doctor_service_history
   Discriminador: ¿la frase trae una FECHA?
   - fecha + guardias/turnos/quiénes trabajaron → calendar_assignments (start_date, end_date).
   - NO USES list_doctors: filtra características del médico (sexo, rango, departamento), no fechas.
   - NO USES doctor_service_history: es el acumulado de UN médico nombrado.

2) DISPONIBILIDAD: DÍA vs MES vs ESTADO DEL SISTEMA
   Tools: doctors_available_on / availability_report_status / list_doctors
   Discriminador: ¿UN día concreto, el MES completo, o ninguno?
   - un día ("hoy", "mañana", "el 5") → doctors_available_on (date).
   - el mes, "quién falta", "quién no reportó" → availability_report_status (month, year).
   - NO USES list_doctors: ahí "disponible" es service_active/pool_active (estado del sistema),
     no disponibilidad reportada por el médico.
   - "disponible" a secas, sin día ni mes → needs_clarification (pregunta cuál).

3) CALENDARIO: ESTADO DEL MES vs GUARDIAS DE FECHAS
   Tools: calendar_status / calendar_assignments
   Discriminador: ¿pide ESTADO/RESUMEN o las GUARDIAS en sí?
   - "cómo va", "estado", "semanas aprobadas", "huecos" → calendar_status (month, year).
   - fechas concretas o un rango → calendar_assignments (start_date, end_date).
   - un mes completo sin pedir estado ni huecos → calendar_assignments con start_date = primer
     día del mes y end_date = último día del mes.

4) SLOT: REPORTÓ vs PUEDE CUBRIR vs UN MÉDICO
   Tools: doctors_available_on / slot_recommendation / slot_explanation
   Discriminador: ¿listado crudo, candidatos evaluados, o un médico nombrado?
   - "quiénes reportaron" → doctors_available_on (date). Crudo: sin evaluar reglas.
   - "quién PUEDE cubrir", "opciones para asignar" + área →
     slot_recommendation (date, service_area).
   - "por qué <médico>", "por qué no <médico>" →
     slot_explanation (date, service_area, doctor_name).
   - Si el bloque requiere service_area, date o doctor_name y la frase no lo trae →
     needs_clarification en vez de adivinar.

5) CARGA: TODOS vs UNO vs MISIÓN
   Tools: workload_ranking / doctor_service_history / mission_candidates
   Discriminador: ¿ranking completo, un médico, o candidatos de misión?
   - "quién lleva más/menos", "top", "corto de meta" → workload_ranking (month, year, criterion).
   - un médico nombrado ("cuántas guardias lleva García") → doctor_service_history (doctor_name).
   - "candidatos para la misión", "quién puede ir" → mission_candidates (mission_date).

6) PENDIENTES: CONFIRMACIÓN vs ENVÍO vs ALERTA
   Tools: confirmation_status / notification_status / action_alerts
   Discriminador: ¿confirmó, se envió, o hay que atenderlo?
   - "confirmó", "falta confirmar", "declinó" → confirmation_status.
   - "notificación", "se envió", "falló el envío" → notification_status.
   - "qué tengo pendiente por atender", "alertas" → action_alerts.
   - "qué está pendiente" sin dominio → action_alerts.

7) REPORTE: DOCUMENTO vs DATOS EN EL CHAT
   Tools: generate_report / calendar_status / list_doctors
   Discriminador: ¿pide un DOCUMENTO o quiere ver los datos?
   - "mándame", "envía", "PDF", "imprime", "reporte de agosto" →
     generate_report (type, month, year).
   - "cómo va", "estado", "información", "cuántos" → calendar_status o list_doctors.
   - NO USES generate_report si quiere los datos en el chat: esa tool produce un PDF."""


class NLUEngine:
    """LLM-first NLU: single call for intent, entities, and tool selection."""

    def __init__(self, llm: LLMProvider) -> None:
        self._llm = llm
        self._tools_prompt = build_tools_prompt()

    def classify(
        self,
        user_text: str,
        *,
        conversation_history: list[dict[str, str]] | None = None,
        system_context: str = "",
    ) -> NLUResult:
        """Classify user message into a tool invocation.

        Args:
            user_text: Raw user message (no pre-processing).
            conversation_history: Prior exchanges as [{"role": "...", "content": "..."}].
            system_context: Domain knowledge string from build_system_context().

        Returns:
            NLUResult with tool name, params, confidence.
        """
        context = self._format_history(conversation_history)
        today = date.today()
        system_prompt = NLU_SYSTEM_PROMPT.format(
            tools_section=self._tools_prompt,
            conversation_context=context,
            system_context=system_context,
            today=today.isoformat(),
            weekday=_WEEKDAYS_ES[today.weekday()],
        )

        messages: list[dict] = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_text},
        ]

        response = self._call_llm(messages)
        return self._parse(response)

    def _format_history(self, history: list[dict[str, str]] | None) -> str:
        if not history:
            return "(primera interacción)"
        lines = []
        for msg in history[-6:]:
            role = "Usuario" if msg.get("role") == "user" else "Bot"
            content = msg.get("content", "")[:200]
            lines.append(f"{role}: {content}")
        return "\n".join(lines)

    def _call_llm(self, messages: list[dict]) -> str:
        """Call the LLM with retry on failure."""
        try:
            response = self._llm.chat_complete(messages, temperature=0.0, json_mode=True)
            return response.strip()
        except Exception:
            try:
                response = self._llm.chat_complete(messages, temperature=0.0, json_mode=False)
                return response.strip()
            except Exception:
                return ""

    def _parse(self, response: str) -> NLUResult:
        """Parse JSON response into NLUResult."""
        if not response:
            return self._fallback()

        parsed = self._extract_json(response)
        if parsed is None:
            return self._fallback()

        return NLUResult(
            tool=parsed.get("tool", "reply"),
            params=parsed.get("params", {}),
            confidence=float(parsed.get("confidence", 0.5)),
            needs_clarification=bool(parsed.get("needs_clarification", False)),
            clarification_question=str(parsed.get("clarification_question", "")),
        )

    def _extract_json(self, text: str) -> dict | None:
        """Extract JSON from text, handling markdown code blocks."""
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            match = re.search(r'\{.*\}', text, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group(0))
                except json.JSONDecodeError:
                    pass
        return None

    def _fallback(self) -> NLUResult:
        """Conservative fallback — ask for clarification."""
        return NLUResult(
            tool="reply",
            params={"response_type": "unknown"},
            confidence=0.0,
            needs_clarification=True,
            clarification_question="No entendí bien tu consulta. ¿Podrías explicarlo de otra forma?",
        )


# ---------------------------------------------------------------------------
# Legacy IntentClassifier — kept for backward compatibility with tests
# ---------------------------------------------------------------------------

@dataclass
class ClassifiedIntent:
    """Legacy structured intent (kept for test compatibility)."""
    domain: str
    action: str
    metric: str | None = None
    query_type: str | None = None
    params: dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    response_text: str | None = None
    format: str | None = None


class IntentClassifier:
    """Legacy domain/metric classifier (backward-compatible wrapper)."""

    def __init__(self, llm: LLMProvider) -> None:
        self._engine = NLUEngine(llm)

    def classify(
        self,
        user_text: str,
        *,
        entity_hints: str = "",
        resolved_entities: dict[str, Any] | None = None,
    ) -> ClassifiedIntent:
        """Classify using the new NLU engine, return legacy format."""
        result = self._engine.classify(user_text)

        # Map tool → domain/metric for backward compat
        tool_to_domain = {
            "list_doctors": "medicos", "count_doctors": "medicos",
            "doctors_by_sex": "medicos", "doctors_by_rank": "medicos",
            "doctors_by_department": "medicos", "doctor_last_service": "medicos",
            "doctor_service_load": "medicos", "unassigned_doctors": "medicos",
            "calendar_assignments": "calendario", "calendar_assigned_count": "calendario",
            "calendar_status": "calendario",
        }
        domain = tool_to_domain.get(result.tool, "general")
        action = "reply" if result.tool == "reply" else (
            "ambiguous" if result.needs_clarification else "query"
        )

        return ClassifiedIntent(
            domain=domain,
            action=action,
            metric=result.tool if result.tool not in ("reply", "sql_query") else None,
            query_type=result.tool if result.tool not in ("reply",) else None,
            params=result.params,
            confidence=result.confidence,
            response_text=result.clarification_question if result.needs_clarification else None,
        )
