"""add calendar_weeks table and calendar_week_id FK

Revision ID: 3d7632021cde
Revises: 58fd13f136af
Create Date: 2026-05-16 12:08:06.967542
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3d7632021cde'
down_revision: str | None = '58fd13f136af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_weeks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('calendar_id', sa.String(length=36), nullable=False),
    sa.Column('calendar_version_id', sa.String(length=36), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_assignments_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name=op.f('fk_calendar_weeks_calendar_id_calendars')),
    sa.ForeignKeyConstraint(['calendar_version_id'], ['calendar_versions.id'], name=op.f('fk_calendar_weeks_calendar_version_id_calendar_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_weeks'))
    )
    op.create_index(op.f('ix_calendar_weeks_calendar_id'), 'calendar_weeks', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_calendar_weeks_calendar_version_id'), 'calendar_weeks', ['calendar_version_id'], unique=False)
    op.add_column('calendar_assignments', sa.Column('calendar_week_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_calendar_assignments_calendar_week_id'), 'calendar_assignments', ['calendar_week_id'], unique=False)
    op.create_foreign_key(op.f('fk_calendar_assignments_calendar_week_id_calendar_weeks'), 'calendar_assignments', 'calendar_weeks', ['calendar_week_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_calendar_assignments_calendar_week_id_calendar_weeks'), 'calendar_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_assignments_calendar_week_id'), table_name='calendar_assignments')
    op.drop_column('calendar_assignments', 'calendar_week_id')
    op.drop_index(op.f('ix_calendar_weeks_calendar_version_id'), table_name='calendar_weeks')
    op.drop_index(op.f('ix_calendar_weeks_calendar_id'), table_name='calendar_weeks')
    op.drop_table('calendar_weeks')
    # ### end Alembic commands ###

