"""add telegram_sessions table

Revision ID: 58fd13f136af
Revises: 20260514_0025
Create Date: 2026-05-14 11:46:07.030605
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '58fd13f136af'
down_revision: str | None = '20260514_0025'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_sessions',
    sa.Column('telegram_user_id', sa.String(length=60), nullable=False),
    sa.Column('session_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id', name=op.f('pk_telegram_sessions'))
    )
    op.drop_index('ix_calendar_assignments_version_id', table_name='calendar_assignments')
    op.create_index(op.f('ix_calendar_assignments_calendar_version_id'), 'calendar_assignments', ['calendar_version_id'], unique=False)
    op.create_index(op.f('ix_calendar_assignments_service_area_id'), 'calendar_assignments', ['service_area_id'], unique=False)
    op.create_unique_constraint('uq_calendar_assignments_version_date_area', 'calendar_assignments', ['calendar_version_id', 'service_date', 'service_area_id'])
    op.drop_index('ix_calendars_status', table_name='calendars')
    op.drop_index('ix_calendars_year_month', table_name='calendars')
    op.drop_index('uq_calendars_year_month_active', table_name='calendars', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ux_confirmation_requests_response_token', table_name='confirmation_requests')
    op.create_unique_constraint(op.f('uq_confirmation_requests_response_token'), 'confirmation_requests', ['response_token'])
    op.drop_constraint('uq_deactivation_reasons_code', 'deactivation_reasons', type_='unique')
    op.drop_index('ix_deactivation_reasons_code', table_name='deactivation_reasons')
    op.create_index(op.f('ix_deactivation_reasons_code'), 'deactivation_reasons', ['code'], unique=True)
    op.drop_constraint('uq_departments_normalized_name', 'departments', type_='unique')
    op.drop_index('ix_departments_normalized_name', table_name='departments')
    op.create_index(op.f('ix_departments_normalized_name'), 'departments', ['normalized_name'], unique=True)
    op.drop_index('ix_doctor_availability_doctor_year_month', table_name='doctor_availability')
    op.drop_index('ix_doctor_availability_type', table_name='doctor_availability')
    op.create_unique_constraint('uq_doctor_availability_monthly', 'doctor_availability', ['doctor_id', 'month', 'year', 'availability_type'])
    op.drop_index('ix_doctor_restrictions_starts_at', table_name='doctor_restrictions')
    op.create_index(op.f('ix_doctor_restrictions_reason_id'), 'doctor_restrictions', ['reason_id'], unique=False)
    op.drop_index('ix_doctors_active', table_name='doctors')
    op.drop_index('ix_doctors_service_active', table_name='doctors')
    op.drop_index('ix_doctors_sex', table_name='doctors')
    op.create_index(op.f('ix_doctors_department_id'), 'doctors', ['department_id'], unique=False)
    op.create_index(op.f('ix_doctors_rank_id'), 'doctors', ['rank_id'], unique=False)
    op.create_index(op.f('ix_doctors_service_inactive_reason_id'), 'doctors', ['service_inactive_reason_id'], unique=False)
    op.create_index(op.f('ix_job_executions_created_at'), 'job_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_executions_status'), 'job_executions', ['status'], unique=False)
    op.drop_index('ix_mission_assignments_deleted_at', table_name='mission_assignments')
    op.create_index(op.f('ix_mission_assignments_mission_date'), 'mission_assignments', ['mission_date'], unique=False)
    op.drop_index('ix_mission_ranking_entries_ranking_id', table_name='mission_candidate_ranking_entries')
    op.create_index(op.f('ix_mission_candidate_ranking_entries_doctor_id'), 'mission_candidate_ranking_entries', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_mission_candidate_ranking_entries_mission_candidate_ranking_id'), 'mission_candidate_ranking_entries', ['mission_candidate_ranking_id'], unique=False)
    op.drop_constraint('uq_mission_candidate_rankings_month_year', 'mission_candidate_rankings', type_='unique')
    op.create_index(op.f('ix_mission_candidate_rankings_calendar_version_id'), 'mission_candidate_rankings', ['calendar_version_id'], unique=False)
    op.create_unique_constraint('uq_ranking_period_version', 'mission_candidate_rankings', ['month', 'year', 'calendar_version_id'])
    op.create_index(op.f('ix_notification_events_assignment_id'), 'notification_events', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_notification_events_created_at'), 'notification_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_events_mission_id'), 'notification_events', ['mission_id'], unique=False)
    op.drop_constraint('uq_ranks_normalized_name', 'ranks', type_='unique')
    op.drop_index('ix_ranks_normalized_name', table_name='ranks')
    op.create_index(op.f('ix_ranks_normalized_name'), 'ranks', ['normalized_name'], unique=True)
    op.create_index(op.f('ix_scheduled_jobs_created_at'), 'scheduled_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_scheduled_for'), 'scheduled_jobs', ['scheduled_for'], unique=False)
    op.drop_constraint('uq_service_areas_code', 'service_areas', type_='unique')
    op.drop_index('ix_service_areas_code', table_name='service_areas')
    op.create_index(op.f('ix_service_areas_code'), 'service_areas', ['code'], unique=True)
    op.drop_constraint('uq_telegram_link_tokens_token', 'telegram_link_tokens', type_='unique')
    op.drop_index('ix_telegram_link_tokens_token', table_name='telegram_link_tokens')
    op.create_index(op.f('ix_telegram_link_tokens_token'), 'telegram_link_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_telegram_link_tokens_created_by'), 'telegram_link_tokens', ['created_by'], unique=False)
    op.drop_index('ix_unresolved_gaps_version_id', table_name='unresolved_gaps')
    op.create_index(op.f('ix_unresolved_gaps_calendar_version_id'), 'unresolved_gaps', ['calendar_version_id'], unique=False)
    op.create_index(op.f('ix_unresolved_gaps_service_area_id'), 'unresolved_gaps', ['service_area_id'], unique=False)
    op.drop_index('ix_users_active', table_name='users')
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_index('ix_users_active', 'users', ['active'], unique=False)
    op.drop_index(op.f('ix_unresolved_gaps_service_area_id'), table_name='unresolved_gaps')
    op.drop_index(op.f('ix_unresolved_gaps_calendar_version_id'), table_name='unresolved_gaps')
    op.create_index('ix_unresolved_gaps_version_id', 'unresolved_gaps', ['calendar_version_id'], unique=False)
    op.drop_index(op.f('ix_telegram_link_tokens_created_by'), table_name='telegram_link_tokens')
    op.drop_index(op.f('ix_telegram_link_tokens_token'), table_name='telegram_link_tokens')
    op.create_index('ix_telegram_link_tokens_token', 'telegram_link_tokens', ['token'], unique=False)
    op.create_unique_constraint('uq_telegram_link_tokens_token', 'telegram_link_tokens', ['token'])
    op.drop_index(op.f('ix_service_areas_code'), table_name='service_areas')
    op.create_index('ix_service_areas_code', 'service_areas', ['code'], unique=False)
    op.create_unique_constraint('uq_service_areas_code', 'service_areas', ['code'])
    op.drop_index(op.f('ix_scheduled_jobs_scheduled_for'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_created_at'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_ranks_normalized_name'), table_name='ranks')
    op.create_index('ix_ranks_normalized_name', 'ranks', ['normalized_name'], unique=False)
    op.create_unique_constraint('uq_ranks_normalized_name', 'ranks', ['normalized_name'])
    op.drop_index(op.f('ix_notification_events_mission_id'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_created_at'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_assignment_id'), table_name='notification_events')
    op.drop_constraint('uq_ranking_period_version', 'mission_candidate_rankings', type_='unique')
    op.drop_index(op.f('ix_mission_candidate_rankings_calendar_version_id'), table_name='mission_candidate_rankings')
    op.create_unique_constraint('uq_mission_candidate_rankings_month_year', 'mission_candidate_rankings', ['month', 'year'])
    op.drop_index(op.f('ix_mission_candidate_ranking_entries_mission_candidate_ranking_id'), table_name='mission_candidate_ranking_entries')
    op.drop_index(op.f('ix_mission_candidate_ranking_entries_doctor_id'), table_name='mission_candidate_ranking_entries')
    op.create_index('ix_mission_ranking_entries_ranking_id', 'mission_candidate_ranking_entries', ['mission_candidate_ranking_id'], unique=False)
    op.drop_index(op.f('ix_mission_assignments_mission_date'), table_name='mission_assignments')
    op.create_index('ix_mission_assignments_deleted_at', 'mission_assignments', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_job_executions_status'), table_name='job_executions')
    op.drop_index(op.f('ix_job_executions_created_at'), table_name='job_executions')
    op.drop_index(op.f('ix_doctors_service_inactive_reason_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_rank_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_department_id'), table_name='doctors')
    op.create_index('ix_doctors_sex', 'doctors', ['sex'], unique=False)
    op.create_index('ix_doctors_service_active', 'doctors', ['service_active'], unique=False)
    op.create_index('ix_doctors_active', 'doctors', ['active'], unique=False)
    op.drop_index(op.f('ix_doctor_restrictions_reason_id'), table_name='doctor_restrictions')
    op.create_index('ix_doctor_restrictions_starts_at', 'doctor_restrictions', ['starts_at'], unique=False)
    op.drop_constraint('uq_doctor_availability_monthly', 'doctor_availability', type_='unique')
    op.create_index('ix_doctor_availability_type', 'doctor_availability', ['availability_type'], unique=False)
    op.create_index('ix_doctor_availability_doctor_year_month', 'doctor_availability', ['doctor_id', 'year', 'month'], unique=False)
    op.drop_index(op.f('ix_departments_normalized_name'), table_name='departments')
    op.create_index('ix_departments_normalized_name', 'departments', ['normalized_name'], unique=False)
    op.create_unique_constraint('uq_departments_normalized_name', 'departments', ['normalized_name'])
    op.drop_index(op.f('ix_deactivation_reasons_code'), table_name='deactivation_reasons')
    op.create_index('ix_deactivation_reasons_code', 'deactivation_reasons', ['code'], unique=False)
    op.create_unique_constraint('uq_deactivation_reasons_code', 'deactivation_reasons', ['code'])
    op.drop_constraint(op.f('uq_confirmation_requests_response_token'), 'confirmation_requests', type_='unique')
    op.create_index('ux_confirmation_requests_response_token', 'confirmation_requests', ['response_token'], unique=True)
    op.create_index('uq_calendars_year_month_active', 'calendars', ['year', 'month'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_calendars_year_month', 'calendars', ['year', 'month'], unique=False)
    op.create_index('ix_calendars_status', 'calendars', ['status'], unique=False)
    op.drop_constraint('uq_calendar_assignments_version_date_area', 'calendar_assignments', type_='unique')
    op.drop_index(op.f('ix_calendar_assignments_service_area_id'), table_name='calendar_assignments')
    op.drop_index(op.f('ix_calendar_assignments_calendar_version_id'), table_name='calendar_assignments')
    op.create_index('ix_calendar_assignments_version_id', 'calendar_assignments', ['calendar_version_id'], unique=False)
    op.drop_table('telegram_sessions')
    # ### end Alembic commands ###

