"""add escalated_at, user whatsapp_phone/permissions, and area start_hour

Revision ID: 8b3499ae4707
Revises: 20260523_0035
Create Date: 2026-05-23 14:42:42.340679
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8b3499ae4707'
down_revision: str | None = '20260523_0035'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_calendar_weeks_version_week', 'calendar_weeks', ['calendar_version_id', 'week_number'])
    op.add_column('confirmation_requests', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_confirmation_requests_escalated_at'), 'confirmation_requests', ['escalated_at'], unique=False)

    # Add start_hour as nullable first to handle existing rows
    op.add_column('service_areas', sa.Column('start_hour', sa.Integer(), nullable=True))
    op.execute("UPDATE service_areas SET start_hour = 7 WHERE start_hour IS NULL")
    op.alter_column('service_areas', 'start_hour', nullable=False)

    op.add_column('users', sa.Column('whatsapp_phone', sa.String(length=40), nullable=True))

    # Add permissions as nullable first to handle existing rows
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True))
    op.execute("UPDATE users SET permissions = '[]'::json WHERE permissions IS NULL")
    op.alter_column('users', 'permissions', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'whatsapp_phone')
    op.drop_column('service_areas', 'start_hour')
    op.drop_index(op.f('ix_confirmation_requests_escalated_at'), table_name='confirmation_requests')
    op.drop_column('confirmation_requests', 'escalated_at')
    op.drop_constraint('uq_calendar_weeks_version_week', 'calendar_weeks', type_='unique')
    # ### end Alembic commands ###

